FROM centos:8
RUN yum -y update

# Install OpenSSH server
RUN yum install -y openssh-server epel-release libffi-devel gcc

# Install Ansible
RUN yum install -y python3-pip python3-devel openssl-devel
#software-properties-common git  python-dev libffi-dev libssl-dev
RUN pip3 install -U setuptools
RUN pip3 install 'ansible~=2.9.0'
RUN alternatives --set python /usr/bin/python3

# Install Ansible inventory file
RUN mkdir /etc/ansible/ && echo "localhost ansible_connection=local" > /etc/ansible/hosts
