FROM ubuntu:24.04
RUN apt-get update

# Install OpenSSH server
RUN apt-get install -y openssh-server

# Install Ansible
RUN apt-get install -y pipx software-properties-common git python3-pip python3-dev libffi-dev libssl-dev
RUN pipx ensurepath
RUN pipx install 'ansible~=12.0.0'

# Install Ansible inventory file
RUN mkdir /etc/ansible/ && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
